from pathlib import Path
from datetime import datetime
import html
import json
## THIS IS IA GENERATED, for readablity purposes 

def generate_report(findings, output_file="report.html"):
    output_path = Path(output_file)

    report_date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    bola_count = sum(1 for finding in findings if finding.vulnerability == "BOLA")
    bfla_count = sum(1 for finding in findings if finding.vulnerability == "BFLA")

    findings_html = ""

    if not findings:
        findings_html = """
        <div class="empty">
            No vulnerabilities were found.
        </div>
        """

    for index, finding in enumerate(findings, start=1):
        findings_html += build_finding_html(finding, index)

    page = f"""
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>API Auditor Report</title>

    <style>
        body {{
            font-family: Arial, sans-serif;
            background: #f4f6f8;
            margin: 0;
            color: #222;
        }}

        header {{
            background: #1f2937;
            color: white;
            padding: 30px;
        }}

        header h1 {{
            margin: 0;
        }}

        header p {{
            margin-top: 8px;
            color: #d1d5db;
        }}

        .container {{
            width: 90%;
            max-width: 1200px;
            margin: 30px auto;
        }}

        .summary {{
            display: flex;
            gap: 20px;
            margin-bottom: 30px;
        }}

        .summary-card {{
            background: white;
            padding: 20px;
            border-radius: 8px;
            flex: 1;
            box-shadow: 0 2px 8px rgba(0, 0, 0, 0.08);
        }}

        .summary-card h2 {{
            margin: 0;
            font-size: 32px;
        }}

        .summary-card p {{
            margin-bottom: 0;
            color: #666;
        }}

        .finding {{
            background: white;
            margin-bottom: 25px;
            border-radius: 8px;
            overflow: hidden;
            box-shadow: 0 2px 8px rgba(0, 0, 0, 0.08);
        }}

        .finding-header {{
            padding: 18px 22px;
            background: #e5e7eb;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }}

        .finding-header h2 {{
            margin: 0;
        }}

        .finding-body {{
            padding: 22px;
        }}

        .row {{
            margin-bottom: 12px;
        }}

        .label {{
            font-weight: bold;
        }}

        .confidence {{
            padding: 5px 10px;
            border-radius: 5px;
            background: #fee2e2;
            color: #991b1b;
            font-weight: bold;
        }}

        pre {{
            background: #111827;
            color: #e5e7eb;
            padding: 15px;
            border-radius: 6px;
            overflow-x: auto;
            white-space: pre-wrap;
            word-break: break-word;
        }}

        .empty {{
            background: white;
            padding: 30px;
            text-align: center;
            border-radius: 8px;
        }}

        footer {{
            text-align: center;
            padding: 25px;
            color: #777;
        }}
    </style>
</head>

<body>

<header>
    <h1>API Auditor Security Report</h1>
    <p>Generated on {report_date}</p>
</header>

<div class="container">

    <div class="summary">

        <div class="summary-card">
            <h2>{len(findings)}</h2>
            <p>Total Findings</p>
        </div>

        <div class="summary-card">
            <h2>{bola_count}</h2>
            <p>BOLA Findings</p>
        </div>

        <div class="summary-card">
            <h2>{bfla_count}</h2>
            <p>BFLA Findings</p>
        </div>

    </div>

    {findings_html}

</div>

<footer>
    Generated by API Auditor
</footer>

</body>
</html>
"""

    output_path.write_text(page, encoding="utf-8")

    print(f"[+] Report generated: {output_path.resolve()}")

    return output_path


def build_finding_html(finding, index):
    endpoint = finding.endpoint
    evidence = finding.evidence or {}

    vulnerability = finding.vulnerability
    confidence = finding.confidence or "UNKNOWN"

    method = evidence.get("method", getattr(endpoint, "method", "UNKNOWN"))
    path = evidence.get("request_url", getattr(endpoint, "path", "UNKNOWN"))
    status_code = evidence.get("status_code", "N/A")
    request_body = evidence.get("request_body")

    details = ""

    if vulnerability == "BOLA":
        details = build_bola_evidence(evidence)

    elif vulnerability == "BFLA":
        details = build_bfla_evidence(evidence)

    return f"""
    <div class="finding">

        <div class="finding-header">
            <h2>#{index} - {escape(vulnerability)}</h2>
            <span class="confidence">{escape(confidence)}</span>
        </div>

        <div class="finding-body">

            <div class="row">
                <span class="label">Method:</span>
                {escape(method)}
            </div>

            <div class="row">
                <span class="label">Endpoint:</span>
                {escape(path)}
            </div>

            <div class="row">
                <span class="label">HTTP Status:</span>
                {escape(status_code)}
            </div>

            {render_json_block("Request Body", request_body)}

            {details}

        </div>

    </div>
    """


def build_bola_evidence(evidence):
    base_response = evidence.get("base_response_body")
    cross_response = evidence.get("cross_response_body")

    return (
        render_text_block("Victim Baseline Response", base_response)
        + render_text_block("Cross-User Response", cross_response)
    )


def build_bfla_evidence(evidence):
    before = evidence.get("before_response_body")
    attack = evidence.get("attack_response_body")
    after = evidence.get("after_response_body")
    affected = evidence.get("resource_is_affected")

    result = ""

    result += render_text_block("Before Attack", before)
    result += render_text_block("Attack Response", attack)
    result += render_text_block("After Attack", after)

    if affected is not None:
        result += f"""
        <div class="row">
            <span class="label">Resource affected:</span>
            {escape(affected)}
        </div>
        """

    return result


def render_text_block(title, value):
    if value is None:
        return ""

    formatted = pretty_value(value)

    return f"""
    <div class="row">
        <span class="label">{escape(title)}:</span>
        <pre>{escape(formatted)}</pre>
    </div>
    """


def render_json_block(title, value):
    if not value:
        return ""

    formatted = pretty_value(value)

    return f"""
    <div class="row">
        <span class="label">{escape(title)}:</span>
        <pre>{escape(formatted)}</pre>
    </div>
    """


def pretty_value(value):
    if isinstance(value, (dict, list)):
        return json.dumps(value, indent=2, ensure_ascii=False)

    if isinstance(value, str):
        try:
            parsed = json.loads(value)
            return json.dumps(parsed, indent=2, ensure_ascii=False)
        except (json.JSONDecodeError, TypeError):
            return value

    return str(value)


def escape(value):
    return html.escape(str(value))